"""Initial schema with unified product model

Revision ID: 9a5bb11300d5
Revises: 
Create Date: 2026-01-05 21:03:08.145245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5bb11300d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('products', sa.Column('product_type', sa.String(), nullable=False, server_default='PATTERN'))
    op.add_column('products', sa.Column('sanity_document_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('colors_used', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('grid_size', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('products', sa.Column('display_order', sa.Integer(), nullable=True, server_default='0'))

    # Make pattern_id nullable - requires table recreation in SQLite
    with op.batch_alter_table('products', schema=None, copy_from=None) as batch_op:
        batch_op.alter_column('pattern_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)

    # Create index on sanity_document_id
    op.create_index(op.f('ix_products_sanity_document_id'), 'products', ['sanity_document_id'], unique=True)

    # Note: SQLite doesn't support dropping defaults with ALTER COLUMN
    # The server_default will remain in the schema but won't affect new inserts in practice
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sanity_document_id'), table_name='products')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('pattern_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    op.drop_column('products', 'display_order')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'grid_size')
    op.drop_column('products', 'colors_used')
    op.drop_column('products', 'category')
    op.drop_column('products', 'sanity_document_id')
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
